version: '3.8'
services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      DB_TYPE: mysql
      DB_HOST: technicalTest_db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: project_management
      JWT_PRIVATE_KEY: secret
    ports:
      - 4200:4200
    depends_on:
      technicalTest_db:
        condition: service_healthy
    networks:
      - shared-network

  technicalTest_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project_management
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h localhost']
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - shared-network

volumes:
  db-data:

networks:
  shared-network:
    external: true
